In [2]:
import pandas as pd
ar=pd.array(["p","a","d"])
a=pd.Series(ar)     #series adds index 
a

0    p
1    a
2    d
dtype: string

In [ ]:
f=pd.DataFrame() 
print(f)

Empty DataFrame
Columns: []
Index: []

In [ ]:
x=["jay","krish"]
d=pd.DataFrame(x)   #dataframe adds index and col name
print(d)

       0
0    jay
1  krish

In [9]:
xu={"key":["10","20","30"],"name":["jay","wlc","dnd"]}
au=pd.DataFrame(xu)
print(au)

  key name
0  10  jay
1  20  wlc
2  30  dnd

In [9]:
info = {'one' : pd.Series(["10","20","30","40","50","60"], index=['a','b','c','d','e','f']),  
        'two' : pd.Series([1, 2, 3, 4, 5, 6, 7, 8], index=['l','o','k','i','g','z','x',''])}

d1 = pd.DataFrame(info)
print(d1)

print()

print(d1["one"])

   one  two
   NaN  8.0
a   10  NaN
b   20  NaN
c   30  NaN
d   40  NaN
e   50  NaN
f   60  NaN
g  NaN  5.0
i  NaN  4.0
k  NaN  3.0
l  NaN  1.0
o  NaN  2.0
x  NaN  7.0
z  NaN  6.0

     NaN
a     10
b     20
c     30
d     40
e     50
f     60
g    NaN
i    NaN
k    NaN
l    NaN
o    NaN
x    NaN
z    NaN
Name: one, dtype: object

In [34]:
info = {'one' : pd.Series([1, 2, 3, 4, 5, 6], index=['a','b','c','d','e','f']),
        'two' : pd.Series([1, 2, 3, 4, 5, 6, 7, 8], index=['a','b','c','d','e','f','g','h'])}

d1 = pd.DataFrame(info)
print(d1)

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  4.0    4
e  5.0    5
f  6.0    6
g  NaN    7
h  NaN    8

In [ ]:
info = {'one' : pd.Series([1, 2, 3, 4, 5, 6], index=['a','b','c','d','e','f']),
        'two' : pd.Series([1, 2, 3, 4, 5, 6, 7, 8], index=['a','b','c','d','e','f','g','h'])}

d1 = pd.DataFrame(info)
print(d1)



d1["three"]=pd.Series([20,30],index=["a","b"])
print(d1)

print()

d1["four"]=d1["one"]+d1["three"]
print(d1)

print()

del d1['one']
print(d1)

print()

d1.pop('two')
print(d1)   

print()

print(d1.loc["b"])

print()

print(d1.iloc[0])  #iloc is used to access the row by index position and loc is used to access the row by label name

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  4.0    4
e  5.0    5
f  6.0    6
g  NaN    7
h  NaN    8

   one  two  three
a  1.0    1   20.0
b  2.0    2   30.0
c  3.0    3    NaN
d  4.0    4    NaN
e  5.0    5    NaN
f  6.0    6    NaN
g  NaN    7    NaN
h  NaN    8    NaN

   one  two  three  four
a  1.0    1   20.0  21.0
b  2.0    2   30.0  32.0
c  3.0    3    NaN   NaN
d  4.0    4    NaN   NaN
e  5.0    5    NaN   NaN
f  6.0    6    NaN   NaN
g  NaN    7    NaN   NaN
h  NaN    8    NaN   NaN

   two  three  four
a    1   20.0  21.0
b    2   30.0  32.0
c    3    NaN   NaN
d    4    NaN   NaN
e    5    NaN   NaN
f    6    NaN   NaN
g    7    NaN   NaN
h    8    NaN   NaN

   three  four
a   20.0  21.0
b   30.0  32.0
c    NaN   NaN
d    NaN   NaN
e    NaN   NaN
f    NaN   NaN
g    NaN   NaN
h    NaN   NaN

three    30.0
four     32.0
Name: b, dtype: float64

three    20.0
four     21.0
Name: a, dtype: float64

In [4]:
info = {'one' : pd.Series([1, 2, 3, 4, 5, 6], index=['a','b','c','d','e','f']),
        'two' : pd.Series([1, 2, 3, 4, 5, 6, 7, 8], index=['a','b','c','d','e','f','g','h'])}

d1 = pd.DataFrame(info)  


print(d1[1:3])

   one  two
b  2.0    2
c  3.0    3

In [2]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")


df


df[["Name"]]

df[["Name"]][1:10]

                                                Name
1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2                             Heikkinen, Miss. Laina
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                           Allen, Mr. William Henry
5                                   Moran, Mr. James
6                            McCarthy, Mr. Timothy J
7                     Palsson, Master. Gosta Leonard
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                Nasser, Mrs. Nicholas (Adele Achem)

In [3]:


on= pd.Series([10,20,30,40,50,60],index=[1,2,3,4,5,6])
print(on)

om= pd.Series([10,20,30,40,50,60],index=[1,2,3,4,5,6])
print(om)

os=pd.concat([on,om])  #sqare needed 
print(os)
a=[10,]

1    10
2    20
3    30
4    40
5    50
6    60
dtype: int64
1    10
2    20
3    30
4    40
5    50
6    60
dtype: int64
1    10
2    20
3    30
4    40
5    50
6    60
1    10
2    20
3    30
4    40
5    50
6    60
dtype: int64

In [21]:

print(os[1])

print(on*om)

print(on+om)

1    10
1    10
dtype: int64
1     100
2     400
3     900
4    1600
5    2500
6    3600
dtype: int64
1     20
2     40
3     60
4     80
5    100
6    120
dtype: int64

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")


df.drop("PassengerId",axis=1)    #temp delete

df

df.drop("Survived",axis=1,inplace=True)   #pr delete
 
df

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [27]:
df.drop(3)
df

df.drop(3, inplace=True)
df

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,5,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...
886,887,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [29]:
df.set_index("Name",inplace=True)
df

,PassengerId,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,
"Braund, Mr. Owen Harris",1,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Heikkinen, Miss. Laina",3,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
"Allen, Mr. William Henry",5,3,male,35.0,0,0,373450,8.0500,NaN,S
"Moran, Mr. James",6,3,male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...
"Montvila, Rev. Juozas",887,2,male,27.0,0,0,211536,13.0000,NaN,S
"Graham, Miss. Margaret Edith",888,1,female,19.0,0,0,112053,30.0000,B42,S
"Johnston, Miss. Catherine Helen ""Carrie""",889,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
"Behr, Mr. Karl Howell",890,1,male,26.0,0,0,111369,30.0000,C148,C
"Dooley, Mr. Patrick",891,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df.reset_index(inplace=True)


df

,Name,PassengerId,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Braund, Mr. Owen Harris",1,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,"Heikkinen, Miss. Laina",3,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,"Allen, Mr. William Henry",5,3,male,35.0,0,0,373450,8.0500,NaN,S
4,"Moran, Mr. James",6,3,male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...
885,"Montvila, Rev. Juozas",887,2,male,27.0,0,0,211536,13.0000,NaN,S
886,"Graham, Miss. Margaret Edith",888,1,female,19.0,0,0,112053,30.0000,B42,S
887,"Johnston, Miss. Catherine Helen ""Carrie""",889,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
888,"Behr, Mr. Karl Howell",890,1,male,26.0,0,0,111369,30.0000,C148,C
889,"Dooley, Mr. Patrick",891,3,male,32.0,0,0,370376,7.7500,NaN,Q